application: servicize
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /lib/css
  static_dir: lib/css
- url: /lib/img
  static_dir: lib/img
- url: /lib/js
  static_dir: lib/js
- url: .*
  script: main.application

libraries:
- name: django
  version: "1.5"
