application: servicize
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.application
- url: /css
  static_dir: lib/css
- url: /img
  static_dir: lib/img
- url: /js
  static_dir: lib/js

libraries:
- name: django
  version: "1.5"
